---
program_dir: "/opt/bench"

cpu_governor: "performance"

openblas_version: "0.3.21"
openblas_name: "OpenBLAS-{{ openblas_version }}"

hpl_version: "2.3"
hpl_name: "hpl-{{ hpl_version }}"

hpcg_version: "3-1-0"
hpcg_archive_name: "HPCG-release-{{ hpcg_version }}"
hpcg_name: "hpcg-{{ hpcg_archive_name }}"

compile_flags: "-Ofast -march=native -fno-stack-protector -z execstack -no-pie -fomit-frame-pointer -funroll-loops -ffast-math -ftree-vectorize"

ram_in_gb: "{{ ( ansible_memtotal_mb / 1024 * 0.75 ) | int | abs }}"

nodecount: "{{ ansible_play_hosts | length | int }}"

hpl_config:
  Ns: "{{ (((((ram_in_gb | int) * 1024 * 1024 * 1024 * (nodecount | int)) / 8) | root) * 0.90) | int }}"
  num_of_NBs: 2
  NBs: 256 384
  Ps: 1
  Qs: 1
