---
program_dir: "/opt/bench"

openblas_version: "0.3.21"
openblas_name: "OpenBLAS-{{ openblas_version }}"

ram_in_gb: "{{ ( ansible_memtotal_mb / 1024 * 0.75 ) | int | abs }}"

nodecount: "{{ ansible_play_hosts | length | int }}"

hpl_config:
  N: "{{ (((((ram_in_gb | int) * 1024 * 1024 * 1024 * (nodecount | int)) / 8) | root) * 0.90) | int }}"
  NB: 256
  P: 1
  Qs: 8
