---
- name: Install hpl benchmark
  hosts: cluster
  become: false
  tags: ['setup']

  vars_files: ['config.yml']

  tasks:
    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      become: true

    - name: Install dependencies
      ansible.builtin.package:
        name:
          - build-essential
          - openmpi-bin
        state: present
      become: true

    - name: Create benchmark directory
      ansible.builtin.file:
        path: "{{ program_dir }}"
        state: directory
        owner: "{{ ansible_user | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"
        group: "{{ ansible_user | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"
        mode: 0755
      become: true

    - name: Download OpenBlas
      ansible.builtin.unarchive:
        src: "https://github.com/xianyi/OpenBLAS/releases/download/v{{ openblas_version }}/{{ openblas_name }}.tar.gz"
        dest: "{{ program_dir }}"
        remote_src: true
        creates: "{{ program_dir }}/{{ openblas_name }}/README.md"

# https://github.com/bgeneto/build-install-compile-openblas
    - name: Build OpenBlas
      ansible.builtin.command: "make USE_THREAD=1 NUM_THREADS=8 USE_OPENMP=0 DYNAMIC_ARCH=0 COMMON_OPT='-Ofast -march=native -fno-stack-protector -z execstack -no-pie' CFLAGS='-Ofast -march=native -fno-stack-protector -z execstack -no-pie' FCOMMON_OPT='-Ofast -march=native -fno-stack-protector -z execstack -no-pie' FCFLAGS='-Ofast -march=native -fno-stack-protector -z execstack -no-pie'"
      args:
        chdir: "{{ program_dir }}/{{ openblas_name }}"
        creates: "{{ program_dir }}/{{ openblas_name }}/libopenblas.a"
      
